# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
project: tm70

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
shortpath: /scratch/tm70

queue: express
ncpus: 96
jobfs: 10GB
mem: 384GB

walltime: 01:00:00
jobname: 025deg_jra55do_ryf

model: access-om3

exe: /g/data/ik11/spack/0.20.1/opt/linux-rocky8-cascadelake/intel-2021.6.0/access-om3-main-lxbeca7/bin/access-om3-MOM6-CICE6
input: 
    - /g/data/tm70/ml0072/COMMON/INPUTS/025deg/ocean_vgrid_50/025deg/share # shared grids and topography
    - /g/data/tm70/ml0072/COMMON/INPUTS/025deg/ocean_vgrid_50/025deg/mom # grids, ICs etc
    - /g/data/tm70/ml0072/COMMON/INPUTS/025deg/ocean_vgrid_50/025deg/cice # grids, ICs etc
    - /g/data/tm70/ml0072/COMMON/INPUTS/025deg/ocean_vgrid_50/025deg/share/meshes/JRA55do-ESMFmesh.nc # mesh for JRA55-do stream
    - /g/data/ik11/inputs/JRA-55/RYF/v1-4 # datm and drof JRA55-do streams data
 
collate: false
runlog: true

userscripts:
    setup: ./setup_cice_restarts.sh
    archive: ./archive_cice_restarts.sh

modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/0.x.0/linux-rocky8-cascadelake
  load:
      - intel-compiler/2021.6.0
      - openmpi/4.1.4
      - parallelio/2.5.10
